### ISSUE TITLE
Default to application/x-www-form-urlencoded on verification

### ISSUE THREAD

**Issue by Zegnat** [Inklings-io/selfauth#12]
I ran into this when testing against [Telegraph](https://telegraph.p3k.io/). It sends an Accept header with `*/*` but does not accept the JSON response (it seems).

Should we just default to `application/x-www-form-urlencoded` on the [auth code verification](http://indieweb.org/authorization-endpoint#Auth_code_verification) step unless the Accept header specifies `application/json`?

**Comment by sknebel** [comment]
if it claims to accept `*/*` that sounds like a bug in Telegraph, and and if I remember right I've seen other implementations that default to JSON (could be confusing it with token endpoints though). We should support both, but I'm not sure the default matters. /cc @aaronpk

**Comment by aaronpk** [comment]
Yeah sounds like Telegraph needs to send a better `Accept` header. Feel free to file an issue there and reference this one.

**Comment by Zegnat** [comment]
Is there a preferred default though, @aaronpk? For those that do `Accept: */*`, or include neither `application/x-www-form-urlencoded` nor `application/json`?

Although in the case of the latter, we should probably just error with `406 Not Acceptable`.

**Comment by Zegnat** [comment]
[indieauth/client](https://github.com/indieweb/indieauth-client-php/) supports JSON responses since [version 0.2.0](https://github.com/indieweb/indieauth-client-php/releases/tag/0.2.0). Versions before that relied on `application/x-www-form-urlencoded`, which leads to problems in e.g. Telegraph.

That might be a reason for us to default to form encoding and only send JSON when requested.

**Comment by Zegnat** [comment]
Going to close this issue. As per https://github.com/indieweb/indieauth/issues/18#issuecomment-665911198 the specification is more than likely to stop allowing form encoded responses completely.
