### ISSUE TITLE
Add warning on setup.php for unsafe PHP versions

### ISSUE THREAD

**Issue by Zegnat** [Inklings-io/selfauth#14]
We should be clear when the system has to fallback to less safe methods.

1. When `random_bytes` and `openssl_random_pseudo_bytes` are unavailable, the key cannot be claimed to be cryptographically secure. (Is it still secure enough? Who knows. Up to the user to decide.)
2. When `hash_equals` is unavailable, the code comparison is vulnerable to timing attacks. Although this is mitigated (a little) by having the codes be time sensitive so a full on attack is harder.

In those cases there should be a warning on top of the setup.php page.

Because we do not want to leak information about the PHP version on the server later on, setup.php must be disabled when config.php exists.

**Comment by dissolve** [comment]
not when it exists, but when configured (already a boolean) in the code, this way a blank file doesn't break it

**Comment by Zegnat** [comment]
This landed through https://github.com/Inklings-io/selfauth/commit/d299becf4c1d798d1eddaf812b1448813ac7a28e.
