### ISSUE TITLE
use hash_equals() in verify_password()

### ISSUE THREAD

**Issue by sebsel** [Inklings-io/selfauth#17]
`verify_signed_code()` uses `hash_equals()` if the function exists, but `verify_password()` should too

https://github.com/Inklings-io/selfauth/blob/d3ea7d774faac56a61b270d1cd09401cea12df0b/index.php#L63

**Comment by Zegnat** [comment]
Putting this here so I don’t forget, I [already have](https://gist.github.com/Zegnat/5935844#file-bcrypt-php-L58-L63) a semi-`hash_equals` polyfill in the public domain:

```php
$password_length = strlen($password = crypt($password, $stored_hash) . chr(0));
$stored_hash_length = strlen($stored_hash .= chr(0));
$result = $password_length - $stored_hash_length;
for ($i = 0; $i < 60; $i++) {
    $result |= (ord($stored_hash[$i % $stored_hash_length]) ^ ord($password[$i % $password_length]));
}
```

It would need a little tweaking and obviously doesn’t cover every imaginable edge-case (like `strlen` problems) covered by [password_compat](https://github.com/ircmaxell/password_compat) but it would work as a quick redefine of `hash_equals` for legacy PHP versions.
