### ISSUE TITLE
write the config file if the server has write permissions

### ISSUE THREAD

**Issue by aaronpk** [Inklings-io/selfauth#3]
you can skip the manual copy-paste step if the web server has write permissions in the folder! check if the file is writable, and the setup script can write the file itself. (of course it should only do this if there aren't already values defined). on hosts like dreamhost, the web server is running as the same user account as the user's sftp account, so would work seamlessly there.

**Comment by dissolve** [comment]
Definitely would like to see this

**Comment by dissolve** [comment]
Closing this, as this was added last week.
