### ISSUE TITLE
'How it works' in README unclear

### ISSUE THREAD

**Issue by ScalaWilliam** [Inklings-io/selfauth#32]
I couldn't understand what it means.

There's no mention of authorization_endpoint on https://indieauth.com/setup

Also would be helpful to have a list of users of this package, I generally work better by inspecting the usage first-hand.

**Comment by Zegnat** [comment]
This repo has nothing to do with [IndieAuth.com](https://indieauth.com/) (which will be renamed IndieLogin.com to counter this confusion).

[IndieAuth](http://indieweb.org/indieauth) is a protocol that this package implements through a simple password login, much like how IndieAuth.com implements it through [RelMeAuth](http://indieweb.org/RelMeAuth).

Except for the test form under <b>How it works</b> the README doesn’t link to IndieAuth.com or mentions it at all, so I am not sure why you would read https://indieauth.com/setup when you want to set-up Selfauth?

I am using this package to login where IndieAuth is supported (e.g. IndieWeb wiki, Telegraph Webmention sending), see `http://vanderven.se/martijn/`.

(Aside: the IndieAuth.com setup guide leaving out endpoint discovery [might be a problem by itself](https://indieweb.org/IndieAuth#how_to_should_include_endpoint_definition).)

**Comment by ScalaWilliam** [comment]
Ah. It said IndieAuth and also linked to IndieWeb, so I thought this is some new feature for indieauth.com that I wasn't aware of, hence why I went there to check.

**Comment by sebsel** [comment]
This is a common mistake. It's not strange that people think IndieAuth and IndieAuth.com are the same thing. I think we should add a note under "How it works" (like on https://indieweb.org/IndieAuth) to explain this, at least until IndieAuth.com gets renamed to IndieLogin.com.
