### ISSUE TITLE
base64 encode the scopes?

### ISSUE THREAD

**Issue by sebsel** [Inklings-io/selfauth#35]
Per discussion in #indieweb-dev: https://chat.indieweb.org/dev/2017-08-20#t1503263942259000

A code looks like this, at the moment:
```
599a94f3:4a6a033c2f5303cd38ca6d617a23c1690b31dae3cd54758406a4b70b70fe11a9:create update
```

It might be better to base64 encode the last part of the token, so that it does not contain spaces. Benefits:
- improve copy-paste by humans, because there is no space
- the whole thing looks like one thing

Counter:
- people can't see the scopes (but it's a short lived token anyway)

This came up because with http://gimme-a-token.5eb.nl/ you can issue a token manually, but the Javascript URLdecoder does not see `+` as space.

**Comment by sknebel** [comment]
Encode them where? Context isn't clear to me.

**Comment by sebsel** [comment]
Sorry, I just wanted to note it down quickly. Updated the text.
