### ISSUE TITLE
Merge policy.

### ISSUE THREAD

**Issue by Zegnat** [Inklings-io/selfauth#4]
Can we cobble together a policy for merging things? I didn’t want to start pulling in PRs in case @dissolve has a default way of handling commits on Inklings-io…

**Comment by dissolve** [comment]
I haven't hit the issue yet as no one has had write access.  It's a small enough lib that I'm fine with it being community managed.  So go for it

**Comment by dissolve** [comment]
Oops didn't mean to close it

**Comment by aaronpk** [comment]
the most important thing is a contributing.md file saying that contributors either give up all rights to their contributions or allow their contributions to be licensed under the same license as the project.

**Comment by dissolve** [comment]
+1 I'm open to whatever if someone has something in mind

**Comment by dissolve** [comment]
added a contributing.md and license information that i think all seems reasonable

**Comment by sknebel** [comment]
After today, I'd say as a rule we should do everything in PRs reviewed by someone else 😝

**Comment by dissolve** [comment]
:+1:

**Comment by Zegnat** [comment]
1. Make a new branch, commit changes to it, open PR with reviewers added.
2. After all reviewers green lit the PR, hit the big green merge button on GitHub.
3. Hit the GitHub provided button to remove the now-merged branch.

That sound good to everyone?

**Comment by dissolve** [comment]
Can set this in the repo configs to only allow merging after at least one
reviewer who is not the original commit creator

**Comment by Zegnat** [comment]
> Can set this in the repo configs to only allow merging after at least one reviewer who is not the original commit creator

Go for it :+1:

**Comment by dissolve** [comment]
I think that will do it... never set it up before
