### ISSUE TITLE
Add token endpoint functionality?

### ISSUE THREAD

**Issue by skpy** [Inklings-io/selfauth#45]
I realize that selfauth is not currently a token endpoint, but are you open to exploring how it might provide that functionality?  I think a [self-encoded token](https://indieweb.org/token-endpoint#Self-Encoded_Tokens) served from selfauth would be very helpful.

**Comment by sknebel** [comment]
FWIW, @Zegnat created https://github.com/Zegnat/php-mintoken as a token endpoint with similar goals as selfauth.
