### ISSUE TITLE
Needs updating for the latest IndieAuth changes

### ISSUE THREAD

**Issue by fluffy-critter** [Inklings-io/selfauth#48]
As of this past weekend, requesting an `id` has been deprecated in favor of requesting a `code` with no `scope`.

SelfAuth (formerly-correctly) responds with an error in the latter case, and it seems to be the only commonly-used endpoint which does, which makes for a difficult incompatibility with this protocol change since there's no way for the client to even know a scopeless `code` request failed and needs to fall back to an `id` request.

**Comment by sknebel** [comment]
Seems like that's #46 ?

**Comment by fluffy-critter** [comment]
Ah, so it is! Bit of a race condition -- I had drafted this issue last night but didn't get around to submitting it until just now, and in the meantime a pull request got opened. :) I guess I can close this issue then.
