### ISSUE TITLE
Add CC0?

### ISSUE THREAD

**Issue by Zegnat** [Inklings-io/selfauth#5]
As per [indieweb/wiki#39](https://github.com/indieweb/wiki/issues/39), I would love if we could all just dedicate our code to the public domain. Whether through CC0 or Unlicensed or just a formal statement.

I think the idea behind selfauth would be to stay as small and simple as possible? In that case making the code unencumbered for others to be allowed to build upon would make sense to me.

Discuss.

**Comment by dissolve** [comment]
I'm fine duel licensing with CC0, but as I understand it, it can be difficult still legally.  There is some part missing which is why it's not OSI approved.

**Comment by dissolve** [comment]
adding CC0 and MIT as both licensing options.  Seem good to you?

**Comment by sknebel** [comment]
dual-license MIT and CC0 is acceptable for me as well.
