### ISSUE TITLE
Do not ship with config.php

### ISSUE THREAD

**Issue by sebsel** [Inklings-io/selfauth#7]
The shared host I tested on has a strong opcache, and since config.php is a php file, it caches it.

Maybe check if it exists, if not, create. And add "create a file named config.php" to the instructions.

Also, at this moment, @dissolve committed some test-values (by accident?), so when it knows how to handle a non-existing config.php, you can .gitignore it.
https://github.com/Inklings-io/selfauth/commit/b9e4008fc490c08f3739a29370e08e955d41322d#diff-9e5e2527d69c009a81b8ecd730f3957e

**Comment by sebsel** [comment]
I now saw that it's already in the .gitignore, but hasn't been deleted from the repo yet.

Still: we need to teach setup.php what to do when there's no config.php. 

At this point, we check with `is_writeable()` [here](https://github.com/Inklings-io/selfauth/blob/0aaf45123547b91de223d37bc4613865cca9e910/setup.php#L55), but that one "[Returns TRUE if the filename exists and is writable.](https://secure.php.net/manual/en/function.is-writable.php)", so that's not a good check.

**Comment by dissolve** [comment]
closing this issue, as we no longer include config.php in the repo
